### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by Veyz** [sobatdata/Guna.UI-Framework-Lib#1]
Can you help me with this error in c#? : https://imgur.com/auHAnWw

**Comment by sobatdata** [comment]
yes, so what's the problem?

Pada tanggal Sen, 26 Agt 2019 18.40, KryptedRTX <notifications@github.com>
menulis:

**Comment by sobatdata** [comment]
> Can you help me with this error in c#? : https://imgur.com/auHAnWw

This is the correct code:

  private void Form1_Load(object sender, EventArgs e)
        {
            Guna.UI.Lib.GraphicsHelper.ShadowForm(this);
        }

**Comment by Veyz** [comment]
and how to move the form ?

**Comment by sobatdata** [comment]
> and how to move the form ?

  Guna.UI.WinForms.GunaDragControl gunaDragControl1 = new Guna.UI.WinForms.GunaDragControl(this.components);
            gunaDragControl1.TargetControl = this;

**Comment by Veyz** [comment]
Thanks you very much !

**Comment by Veyz** [comment]
System.NullReferenceException: "The object reference is not defined to an instance of an object.

Hmm when I start my program after adding the code I have this error

**Comment by Veyz** [comment]
Okay, I fixed the problem, but my window still doesn't move.

**Comment by Veyz** [comment]
so can you help me with that?

**Comment by sobatdata** [comment]
> so can you help me with that?

For example, maybe this can help:
https://www33.zippyshare.com/v/bqcPzaC4/file.html

or can see the video on my youtube channel:
http://bit.ly/30wfEr0

**Comment by Veyz** [comment]
Thank you very much it works! keep up the great work! I really love Guna, maybe one day there will be a new framework ? :)

**Comment by sobatdata** [comment]
> Thank you very much it works! keep up the great work! I really love Guna, maybe one day there will be a new framework ? :)

yes, you're welcome, right now I'm redeveloping this framework, just wait for the latest version in a few days.
