### ISSUE TITLE
Cannot close form with Alt+F4 shortcut

### ISSUE THREAD

**Issue by roxima** [sobatdata/Guna.UI-Framework-Lib#17]
Put a `gunaTrackbar` control, play with it and you wont be able to close your form with the keyboard shortcuts noted as the trackbar takes control of `Alt` key. Move the focus to another control and you are OK. Is this behaviour expected?!

**Comment by sobatdata** [comment]
sorry, we don't know that yet.  I will fix it soon.

Pada tanggal Kam, 26 Mar 2020 02.30, Roxima <notifications@github.com>
menulis:
