### ISSUE TITLE
Tab indication

### ISSUE THREAD

**Issue by dddns** [sobatdata/Guna.UI-Framework-Lib#26]
Howdy,

I'm not sure if this is missing or there is another way to to symbolize the control selected, in case buttons.

If i have a form with some buttons, and try to navigate thro them, there's nothing that indicates me that the control is selected, apart from being.
Is there another way, or the standard "selection box" of the standard buttons, could be added to help the user know which button is selected?

Thanks in advanced,

**Comment by sobatdata** [comment]
Hello to the navigation button you can see this video:
https://youtu.be/3R47vB6FmNQ

 We made another solution to find out which button was selected using the
Checked property.  so if the button is selected then the value in the
Checked property = true.

Thank you.

Pada tanggal Jum, 24 Apr 2020 04.02, dddns <notifications@github.com>
menulis:

**Comment by dddns** [comment]
Howdy,

Hum ok,
But, would it be possible to make the color change, when the button get's the focus by the tab control, i mean, the same behavior when the mouse is houver, could be implemented for the control when getting the focus with the tab control.

What do you say?

**Comment by sobatdata** [comment]
Hopefully this source code answers your question
![Capture](https://user-images.githubusercontent.com/35967626/80217285-a4099180-8669-11ea-9dfb-5f32f5ef7c66.JPG)

[TabIndication.zip](https://github.com/sobatdata/Guna.UI-Framework-Lib/files/4529078/TabIndication.zip)

**Comment by sobatdata** [comment]
Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Guna2Button1.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.RadioButton
        Guna2Button2.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.RadioButton
        Guna2Button3.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.RadioButton

        Guna2Button1.CheckedState.FillColor = Color.Red
        Guna2Button2.CheckedState.FillColor = Color.Red
        Guna2Button3.CheckedState.FillColor = Color.Red
    End Sub

    Private Sub Guna2Button1_CheckedChanged(sender As Object, e As EventArgs) Handles Guna2Button1.CheckedChanged
        TabControl1.SelectedIndex = 0
    End Sub

    Private Sub Guna2Button2_CheckedChanged(sender As Object, e As EventArgs) Handles Guna2Button2.CheckedChanged
        TabControl1.SelectedIndex = 1
    End Sub

    Private Sub Guna2Button3_CheckedChanged(sender As Object, e As EventArgs) Handles Guna2Button3.CheckedChanged
        TabControl1.SelectedIndex = 2
    End Sub

**Comment by sobatdata** [comment]
[video.zip](https://github.com/sobatdata/Guna.UI-Framework-Lib/files/4529115/video.zip)

**Comment by dddns** [comment]
Oh, I'm sorry, i may have explained myself wrong.

I mean, imagine you have some buttons on the form, and you press the "tab" keyboard key (not tab control), you don't have nothing to indicate which button in selected.
When the mouse is houver the control, the colour changes, and could be a solution, or the standard "grid" on the control border to indicate that it's selected.

What do you say?


![2020_04_24_14_35_19_Form1](https://user-images.githubusercontent.com/13902147/80218308-ed8db880-8638-11ea-8d17-310a16432db8.jpg)

**Comment by sobatdata** [comment]
[video.zip](https://github.com/sobatdata/Guna.UI-Framework-Lib/files/4529213/video.zip)

**Comment by sobatdata** [comment]
Hello sorry if we misunderstood it, maybe you mean when you press the Tab key then the focus button is the color specified:
[Tab Key Indication.zip](https://github.com/sobatdata/Guna.UI-Framework-Lib/files/4529221/Tab.Key.Indication.zip)

**Comment by sobatdata** [comment]
[tab key indication[video].zip](https://github.com/sobatdata/Guna.UI-Framework-Lib/files/4529232/tab.key.indication.video.zip)

**Comment by dddns** [comment]
Oh ok, chaging the checked state, that's your design right? no way to make this automatic when the control get's the focus?
Just an ideia! and maybe with a property to enable/disable it.

**Comment by sobatdata** [comment]
Thanks to this we will record your request, if possible then we will apply it to several controls in the next version.
